"""Acquisition and parsing of external documentation sources."""

from rail_rag.ingestion.docs.canonical import (
    DEFAULT_PARSED_DIR,
    PARSER_VERSION,
    BBox,
    Block,
    Heading,
    Paragraph,
    ParseManifest,
    TableRow,
    artefact_paths,
    decode_block,
    encode_block,
    read_blocks,
    write_blocks,
)
from rail_rag.ingestion.docs.exceptions import DocumentError, FetchError, ParseError
from rail_rag.ingestion.docs.pdf_reader import (
    Grid,
    Rule,
    TextLine,
    assert_grid_coverage,
    column_edges,
    extract_grid_rows,
    page_grid,
    page_lines,
    page_rules,
    parse_document,
    row_edges,
    running_lines,
)
from rail_rag.ingestion.docs.sources import (
    DocumentSource,
    ParseSpec,
    SectionSpec,
    SourceRegistry,
    load_registry,
    load_source,
)

__all__ = [
    "DEFAULT_PARSED_DIR",
    "PARSER_VERSION",
    "BBox",
    "Block",
    "DocumentError",
    "DocumentSource",
    "FetchError",
    "Heading",
    "Paragraph",
    "ParseError",
    "ParseManifest",
    "ParseSpec",
    "SectionSpec",
    "Grid",
    "Rule",
    "SourceRegistry",
    "TableRow",
    "TextLine",
    "artefact_paths",
    "assert_grid_coverage",
    "column_edges",
    "decode_block",
    "encode_block",
    "extract_grid_rows",
    "load_registry",
    "load_source",
    "page_grid",
    "page_lines",
    "page_rules",
    "parse_document",
    "read_blocks",
    "row_edges",
    "running_lines",
    "write_blocks",
]
